/**
 * Auto-generated icon loaders
 * Generated by scanning: ./src
 *
 * @generated by @phaserjsx/ui/generate-icons
 */
export type IconLoaderFn = () => Promise<{ default: string }>

export const iconLoaders: Record<string, IconLoaderFn> = {
  'bell': () => import('bootstrap-icons/icons/bell.svg' as string),
  'bell-fill': () => import('bootstrap-icons/icons/bell-fill.svg' as string),
  'boxes': () => import('bootstrap-icons/icons/boxes.svg' as string),
  'bricks': () => import('bootstrap-icons/icons/bricks.svg' as string),
  'check': () => import('bootstrap-icons/icons/check.svg' as string),
  'check-circle': () => import('bootstrap-icons/icons/check-circle.svg' as string),
  'check-circle-fill': () => import('bootstrap-icons/icons/check-circle-fill.svg' as string),
  'check-square': () => import('bootstrap-icons/icons/check-square.svg' as string),
  'chevron-down': () => import('bootstrap-icons/icons/chevron-down.svg' as string),
  'circle': () => import('bootstrap-icons/icons/circle.svg' as string),
  'custom-check': () => import('./../custom-icons/custom-check.svg'),
  'dash': () => import('bootstrap-icons/icons/dash.svg' as string),
  'dash-circle-fill': () => import('bootstrap-icons/icons/dash-circle-fill.svg' as string),
  'envelope': () => import('bootstrap-icons/icons/envelope.svg' as string),
  'exclamation-triangle': () => import('bootstrap-icons/icons/exclamation-triangle.svg' as string),
  'file-text': () => import('bootstrap-icons/icons/file-text.svg' as string),
  'gear': () => import('bootstrap-icons/icons/gear.svg' as string),
  'grid': () => import('bootstrap-icons/icons/grid.svg' as string),
  'hand-index': () => import('bootstrap-icons/icons/hand-index.svg' as string),
  'hourglass': () => import('bootstrap-icons/icons/hourglass.svg' as string),
  'house': () => import('bootstrap-icons/icons/house.svg' as string),
  'info-circle': () => import('bootstrap-icons/icons/info-circle.svg' as string),
  'moon': () => import('bootstrap-icons/icons/moon.svg' as string),
  'palette': () => import('bootstrap-icons/icons/palette.svg' as string),
  'person': () => import('bootstrap-icons/icons/person.svg' as string),
  'person-circle': () => import('bootstrap-icons/icons/person-circle.svg' as string),
  'question-circle': () => import('bootstrap-icons/icons/question-circle.svg' as string),
  'square': () => import('bootstrap-icons/icons/square.svg' as string),
  'star': () => import('bootstrap-icons/icons/star.svg' as string),
  'stars': () => import('bootstrap-icons/icons/stars.svg' as string),
  'sun': () => import('bootstrap-icons/icons/sun.svg' as string),
  'toggle-on': () => import('bootstrap-icons/icons/toggle-on.svg' as string),
  'trash': () => import('bootstrap-icons/icons/trash.svg' as string),
  'wifi': () => import('bootstrap-icons/icons/wifi.svg' as string),
}
