/**
 * Auto-generated icon loaders
 * Generated by scanning: ./src
 *
 * @generated by @phaserjsx/ui/generate-icons
 */
export type IconLoaderFn = () => Promise<{ default: string }>

export const iconLoaders: Record<string, IconLoaderFn> = {
  'bell-fill': () => import('bootstrap-icons/icons/bell-fill.svg' as string),
  'boxes': () => import('bootstrap-icons/icons/boxes.svg' as string),
  'bricks': () => import('bootstrap-icons/icons/bricks.svg' as string),
  'check': () => import('bootstrap-icons/icons/check.svg' as string),
  'dash': () => import('bootstrap-icons/icons/dash.svg' as string),
  'gear': () => import('bootstrap-icons/icons/gear.svg' as string),
  'grid': () => import('bootstrap-icons/icons/grid.svg' as string),
  'hand-index': () => import('bootstrap-icons/icons/hand-index.svg' as string),
  'palette': () => import('bootstrap-icons/icons/palette.svg' as string),
  'question-circle': () => import('bootstrap-icons/icons/question-circle.svg' as string),
  'square': () => import('bootstrap-icons/icons/square.svg' as string),
  'stars': () => import('bootstrap-icons/icons/stars.svg' as string),
  'bell-fill': () => import('./public/custom-icons/bell-fill.svg'),
  'boxes': () => import('./public/custom-icons/boxes.svg'),
  'bricks': () => import('./public/custom-icons/bricks.svg'),
  'check': () => import('./public/custom-icons/check.svg'),
  'dash': () => import('./public/custom-icons/dash.svg'),
  'gear': () => import('./public/custom-icons/gear.svg'),
  'grid': () => import('./public/custom-icons/grid.svg'),
  'hand-index': () => import('./public/custom-icons/hand-index.svg'),
  'palette': () => import('./public/custom-icons/palette.svg'),
  'question-circle': () => import('./public/custom-icons/question-circle.svg'),
  'square': () => import('./public/custom-icons/square.svg'),
  'stars': () => import('./public/custom-icons/stars.svg'),
}
