/**
 * Auto-generated icon loader registry
 * Package: bootstrap-icons
 * Icons found: 12
 *
 * @generated by @phaserjsx/ui/generate-icon-loaders
 * @cspell: disable
 */

/**
 * Icon loaders - only icons used in the codebase are registered
 * Bundler will create separate chunks for each icon
 */
export const iconLoaders: Record<string, () => Promise<{ default: string }>> = {
  'bell-fill': () => import('bootstrap-icons/icons/bell-fill.svg'),
  'boxes': () => import('bootstrap-icons/icons/boxes.svg'),
  'bricks': () => import('bootstrap-icons/icons/bricks.svg'),
  'check': () => import('bootstrap-icons/icons/check.svg'),
  'dash': () => import('bootstrap-icons/icons/dash.svg'),
  'gear': () => import('bootstrap-icons/icons/gear.svg'),
  'grid': () => import('bootstrap-icons/icons/grid.svg'),
  'hand-index': () => import('bootstrap-icons/icons/hand-index.svg'),
  'palette': () => import('bootstrap-icons/icons/palette.svg'),
  'question-circle': () => import('bootstrap-icons/icons/question-circle.svg'),
  'square': () => import('bootstrap-icons/icons/square.svg'),
  'stars': () => import('bootstrap-icons/icons/stars.svg'),
}
