/**
 * Generator for icon type definitions from any icon library
 * Scans an icon package and generates TypeScript union type
 *
 * Usage:
 *   generate-icon-types --package bootstrap-icons --output ./src/types/icons.ts
 */
import { readdir, writeFile } from 'node:fs/promises'
import { basename, join, resolve } from 'node:path'
import { parseArgs } from 'node:util'

interface Options {
  package?: string
  directory?: string
  output: string
  typeName?: string
  iconsPath?: string
}

/**
 * Find icon package in node_modules
 */
async function findIconPackage(packageName: string, cwd: string): Promise<string> {
  const fs = await import('node:fs')

  // Try pnpm structure first
  const pnpmBase = join(cwd, 'node_modules/.pnpm')
  if (fs.existsSync(pnpmBase)) {
    const entries = await readdir(pnpmBase)
    for (const entry of entries) {
      if (entry.startsWith(`${packageName}@`)) {
        const packagePath = join(pnpmBase, entry, 'node_modules', packageName)
        if (fs.existsSync(packagePath)) {
          return packagePath
        }
      }
    }
  }

  // Try standard node_modules
  const standardPath = join(cwd, 'node_modules', packageName)
  if (fs.existsSync(standardPath)) {
    return standardPath
  }

  throw new Error(`Could not find package: ${packageName}`)
}

/**
 * Main generator function
 */
async function generateIconTypes(options: Options) {
  try {
    const cwd = process.cwd()
    let iconsDir: string
    let sourceName: string

    if (options.directory) {
      // Scan local directory
      iconsDir = resolve(cwd, options.directory)
      sourceName = options.directory
      console.log(`📁 Scanning directory: ${options.directory}`)
    } else if (options.package) {
      // Find the icon package
      const packagePath = await findIconPackage(options.package, cwd)
      iconsDir = join(packagePath, options.iconsPath || 'icons')
      sourceName = options.package
      console.log(`📦 Scanning package: ${options.package}`)
    } else {
      throw new Error('Either --package or --directory must be specified')
    }
    console.log(`📁 Icons directory: ${iconsDir}`)

    // Read all SVG files
    const files = await readdir(iconsDir)
    const iconNames = files
      .filter((file: string) => file.endsWith('.svg'))
      .map((file: string) => basename(file, '.svg'))
      .sort()

    console.log(`✓ Found ${iconNames.length} icons`)

    // Generate TypeScript code
    const typeDefinition = iconNames.map((name: string) => `  | '${name}'`).join('\n')
    const typeName = options.typeName || 'IconType'

    const output = `/**
 * Auto-generated icon type definitions
 * Source: ${sourceName}
 * Total icons: ${iconNames.length}
 *
 * @generated by @phaserjsx/ui/generate-icon-types
 * @cspell: disable
 */

/**
 * All available icon names from ${sourceName}
 * Type-only definition - no runtime imports, zero bundle impact
 */
export type ${typeName} =
${typeDefinition}
`

    // Write to file
    const outputPath = resolve(cwd, options.output)
    await writeFile(outputPath, output, 'utf-8')

    console.log(`✓ Generated: ${outputPath}`)
    console.log(`✓ Type name: ${typeName}`)
    console.log(`✓ Total icons: ${iconNames.length}`)

    if (iconNames.length > 0) {
      console.log(`  First: ${iconNames[0]}`)
      console.log(`  Last: ${iconNames[iconNames.length - 1]}`)
    }
  } catch (error) {
    console.error('❌ Error generating icon types:', error)
    process.exit(1)
  }
}

// Parse CLI arguments
const { values } = parseArgs({
  options: {
    package: { type: 'string', short: 'p' },
    directory: { type: 'string', short: 'd' },
    output: { type: 'string', short: 'o' },
    typeName: { type: 'string', short: 't' },
    iconsPath: { type: 'string', short: 'i' },
    help: { type: 'boolean', short: 'h' },
  },
})

if (values.help || (!values.package && !values.directory) || !values.output) {
  console.log(`
Usage: generate-icon-types [options]

Options:
  -p, --package <name>      Icon package name (e.g., bootstrap-icons)
  -d, --directory <path>    Local directory with SVG files (alternative to --package)
  -o, --output <path>       Output file path (e.g., ./src/types/icons.ts)
  -t, --typeName <name>     TypeScript type name (default: IconType)
  -i, --iconsPath <path>    Relative path to icons in package (default: icons)
  -h, --help                Show this help message

Examples:
  # From npm package
  generate-icon-types -p bootstrap-icons -o ./src/icon-types.generated.ts

  # From local directory
  generate-icon-types -d ./public/icons -o ./src/icon-types.generated.ts
`)
  process.exit(values.help ? 0 : 1)
}

// Run generator
const options: Options = {
  output: values.output as string,
}

if (values.package) {
  options.package = values.package as string
}

if (values.directory) {
  options.directory = values.directory as string
}

if (values.typeName) {
  options.typeName = values.typeName
}

if (values.iconsPath) {
  options.iconsPath = values.iconsPath
}

generateIconTypes(options)
