#!/usr/bin/env tsx
/**
 * Generator for Bootstrap Icons type definitions
 * Scans bootstrap-icons package and generates TypeScript union type
 * Run with: tsx scripts/generate-icon-types.ts
 */
import { readdir, writeFile } from 'node:fs/promises'
import { basename, join } from 'node:path'

/**
 * Main generator function
 */
async function generateIconTypes() {
  try {
    // Path to bootstrap-icons in pnpm node_modules
    const iconsDir = join(
      process.cwd(),
      'node_modules/.pnpm/bootstrap-icons@1.13.1/node_modules/bootstrap-icons/icons'
    )

    // Read all SVG files
    const files = await readdir(iconsDir)
    const iconNames = files
      .filter((file: string) => file.endsWith('.svg'))
      .map((file: string) => basename(file, '.svg'))
      .sort()

    console.log(`Found ${iconNames.length} Bootstrap icons`)

    // Generate TypeScript code
    const typeDefinition = iconNames.map((name: string) => `  | '${name}'`).join('\n')

    const output = `/**
 * Auto-generated Bootstrap Icons type definitions
 * Total icons: ${iconNames.length}
 *
 * @see https://icons.getbootstrap.com/
 * @generated by scripts/generate-icon-types.ts
 * @cspell: disable
 */

/**
 * All available Bootstrap icon names
 * Type-only definition - no runtime imports, zero bundle impact
 */
export type BootstrapIconType =
${typeDefinition}

/**
 * Alias for backward compatibility
 */
export type IconType = BootstrapIconType
`

    // Write to file
    const outputPath = join(process.cwd(), 'apps/test-ui/src/components/icon-types.generated.ts')
    await writeFile(outputPath, output, 'utf-8')

    console.log(`✓ Generated icon types: ${outputPath}`)
    console.log(`✓ Total icons: ${iconNames.length}`)
    console.log('First 10 icons:', iconNames.slice(0, 10).join(', '))
    console.log('Last 10 icons:', iconNames.slice(-10).join(', '))
  } catch (error) {
    console.error('Error generating icon types:', error)
    process.exit(1)
  }
}

// Run generator
generateIconTypes()
