#!/usr/bin/env tsx
/**
 * Auto-generates icon loader registry from actual icon usage in the codebase
 * Scans all TSX/TS files for Icon component usage and generates loaders
 */
import { readdir, readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

/**
 * Recursively find all TypeScript files
 */
async function findTsFiles(dir: string): Promise<string[]> {
  const files: string[] = []
  const entries = await readdir(dir, { withFileTypes: true })

  for (const entry of entries) {
    const fullPath = join(dir, entry.name)

    if (entry.isDirectory()) {
      // Skip node_modules and dist
      if (entry.name === 'node_modules' || entry.name === 'dist') continue
      files.push(...(await findTsFiles(fullPath)))
    } else if (entry.isFile() && /\.(tsx?|jsx?)$/.test(entry.name)) {
      files.push(fullPath)
    }
  }

  return files
}

/**
 * Extract icon names from file content
 */
function extractIconNames(content: string): Set<string> {
  const iconNames = new Set<string>()

  // Match: <Icon type="icon-name" or <Icon type={'icon-name'}
  const typePattern = /<Icon\s+[^>]*type=(?:["']([^"']+)["']|\{['"]([^"']+)['"]\})/g
  let match: RegExpExecArray | null

  while ((match = typePattern.exec(content)) !== null) {
    const iconName = match[1] || match[2]
    if (iconName) {
      iconNames.add(iconName)
    }
  }

  // Match: themed.xxxIcon ?? 'icon-name' (only if property ends with 'Icon')
  const themedPattern = /themed\.(\w*[Ii]con)\s*\?\?\s*["']([^"']+)["']/g
  while ((match = themedPattern.exec(content)) !== null) {
    iconNames.add(match[2])
  }

  return iconNames
}

/**
 * Main generator function
 */
async function generateIconLoaders() {
  try {
    const srcDir = join(process.cwd(), 'apps/test-ui/src')
    const files = await findTsFiles(srcDir)

    console.log(`Scanning ${files.length} TypeScript files for icon usage...`)

    const allIconNames = new Set<string>()

    for (const file of files) {
      const content = await readFile(file, 'utf-8')
      const icons = extractIconNames(content)
      icons.forEach((icon) => allIconNames.add(icon))
    }

    const iconArray = Array.from(allIconNames).sort()
    console.log(`Found ${iconArray.length} unique icons:`, iconArray)

    // Generate loader code
    const loaders = iconArray
      .map((icon) => `  '${icon}': () => import('bootstrap-icons/icons/${icon}.svg'),`)
      .join('\n')

    const output = `/**
 * Auto-generated icon loader registry
 * Icons found: ${iconArray.length}
 *
 * @generated by scripts/generate-icon-loaders.ts
 * Run: pnpm run generate-icon-loaders
 * @cspell: disable
 */

/**
 * Icon loaders - only icons used in the codebase are registered
 * Vite will create separate chunks for each icon
 */
export const iconLoaders: Record<string, () => Promise<{ default: string }>> = {
${loaders}
}
`

    const outputPath = join(srcDir, 'components/icon-loaders.generated.ts')
    await writeFile(outputPath, output, 'utf-8')

    console.log(`✓ Generated icon loaders: ${outputPath}`)
    console.log(`✓ Registered ${iconArray.length} icons`)
  } catch (error) {
    console.error('Error generating icon loaders:', error)
    process.exit(1)
  }
}

// Run generator
generateIconLoaders()
